### ISSUE TITLE
HUD

### ISSUE THREAD

**Issue by voxelv** [voxelv/MacroMachine#1]
Create a HUD (Heads Up Display) to interact with the game using buttons instead of keys.

**Comment by Ghost4dot2** [comment]
Setting up some tasks?

**Comment by voxelv** [comment]
Yeah, just getting a list of things to do down. Github has a nice "issue"
manager that makes it easy to do that.
It's kindof a software engineering thing too, and I found it useful for
keeping track of "what was I up to again?" lol.

-T

**Comment by Ghost4dot2** [comment]
Lol that's pretty awesome

**Comment by voxelv** [comment]
_cleaning up issues I've created. Closing as "stale"_
